Update build

diff --git a/build b/build
--- a/build
+++ b/build
@@ -31,15 +31,15 @@ else
 	exit 1
 fi
 
-cd "$(pwd)/PSACBuild" || echo "${RED}${BOLD}ERROR${RESET}: ${BOLD}$BUILDPATH not found${RESET}" || exit 1
+cd "$(pwd)/PSACBuild" || echo "${RED}${BOLD}ERROR${RESET}: ${BOLD}$BUILDPATH not found${RESET}" && exit 1
 
 # Build
 
-if type "mvn" > /dev/null 2>&1; then
+if type "mvn" > /dev/null 2>&1 && type "make" > /dev/null 2>&1; then
   mvn package && \
   echo "${GREEN}${BOLD}SUCCESS${RESET}: PeyangSuperbAntiCheat build completed successfly." && \
   exit 0
   echo "${RED}${BOLD}ERROR${RESET}: ${BOLD}Unknown error occured"
 else
-  echo "${RED}${BOLD}ERROR${RESET}: ${BOLD}maven${RESET} required"
+  echo "${RED}${BOLD}ERROR${RESET}: ${BOLD}maven${RESET} and ${BOLD}make${RESET} required"
 fi
